# Generated by Django 4.1.2 on 2022-10-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_aap_id_alter_carotenoids_id_alter_eof_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aap",
            name="id",
        ),
        migrations.RemoveField(
            model_name="carotenoids",
            name="id",
        ),
        migrations.RemoveField(
            model_name="eof",
            name="id",
        ),
        migrations.RemoveField(
            model_name="fap",
            name="id",
        ),
        migrations.RemoveField(
            model_name="fsv",
            name="id",
        ),
        migrations.RemoveField(
            model_name="mte",
            name="id",
        ),
        migrations.RemoveField(
            model_name="oa",
            name="id",
        ),
        migrations.RemoveField(
            model_name="opps",
            name="id",
        ),
        migrations.RemoveField(
            model_name="pp",
            name="id",
        ),
        migrations.RemoveField(
            model_name="ppdf",
            name="id",
        ),
        migrations.RemoveField(
            model_name="sis",
            name="id",
        ),
        migrations.RemoveField(
            model_name="wsv",
            name="id",
        ),
        migrations.AlterField(
            model_name="aap",
            name="name",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="carotenoids",
            name="name",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="eof",
            name="name",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="fap",
            name="name",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="fsv",
            name="name",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="mte",
            name="name",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="oa",
            name="name",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="opps",
            name="name",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="pp",
            name="name",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ppdf",
            name="name",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="sis",
            name="name",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="wsv",
            name="name",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
