# Generated by Django 4.1.2 on 2022-10-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_aap_id_remove_carotenoids_id_remove_eof_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ppdf",
            name="energy",
            field=models.FloatField(null = True),
        ),
    ]
