# Generated by Django 4.1.2 on 2022-10-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_ppdf_energy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ppdf",
            name="df_soluble",
            field=models.FloatField(null=True),
        ),
    ]
