# Generated by Django 4.1.2 on 2022-10-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_ppdf_df_soluble"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ppdf",
            name="water",
            field=models.FloatField(null=True),
        ),
    ]
