# Generated by Django 4.1.2 on 2022-11-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_ppdf_ash_alter_ppdf_carbohydrates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wsv",
            name="Ascorbic_Acid",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="wsv",
            name="B6",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="wsv",
            name="Biotin_B7",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="wsv",
            name="Folates_B9",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="wsv",
            name="Niacin_B3",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="wsv",
            name="Pantothenic_Acid_B5",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="wsv",
            name="Riboflavin_B2",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="wsv",
            name="Thiamine_B1",
            field=models.FloatField(null=True),
        ),
    ]
