# Generated by Django 4.1.2 on 2022-11-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_wsv_ascorbic_acid_alter_wsv_b6_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fsv",
            old_name="TOCPHA",
            new_name="TocopherolsA",
        ),
        migrations.RenameField(
            model_name="fsv",
            old_name="TOCPHB",
            new_name="TocopherolsB",
        ),
        migrations.RenameField(
            model_name="fsv",
            old_name="TOCPHD",
            new_name="TocopherolsD",
        ),
        migrations.RenameField(
            model_name="fsv",
            old_name="TOCTRA",
            new_name="TocopherolsG",
        ),
        migrations.RenameField(
            model_name="fsv",
            old_name="TOCPHG",
            new_name="TocotrienolsA",
        ),
        migrations.RenameField(
            model_name="fsv",
            old_name="TOCTRB",
            new_name="TocotrienolsB",
        ),
        migrations.RenameField(
            model_name="fsv",
            old_name="TOCTRG",
            new_name="TocotrienolsD",
        ),
        migrations.RenameField(
            model_name="fsv",
            old_name="TOCTRD",
            new_name="TocotrienolsG",
        ),
    ]
