# Generated by Django 4.1.2 on 2022-11-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_rename_tocpha_fsv_tocopherolsa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fsv",
            name="CHOCAL",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="fsv",
            name="RETOL",
            field=models.FloatField(null=True),
        ),
    ]
