# Generated by Django 4.1.2 on 2022-11-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_fsv_chocal_fsv_retol"),
    ]

    operations = [
        migrations.AddField(
            model_name="fsv",
            name="OHD3_25",
            field=models.FloatField(null=True),
        ),
    ]
