# Generated by Django 4.1.2 on 2022-11-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_fsv_ohd3_25"),
    ]

    operations = [
        migrations.AddField(
            model_name="fap",
            name="Cholestrol",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="fap",
            name="Docosadienoic",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="fap",
            name="Docosahexaenoic",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="fap",
            name="Docosapentaenoic",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="fap",
            name="Eicosapentaenoic",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="fap",
            name="Eicosatrienoic",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="fap",
            name="Pentadecanoic",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="fap",
            name="Undecanoic",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="pp",
            name="Catechin",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="pp",
            name="Ellagic_acid",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="pp",
            name="Epigallocatechin",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="pp",
            name="Epigallocatechin_3_gallate",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="pp",
            name="Gallo_catechin",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="pp",
            name="Gallocatechin_gallate",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="pp",
            name="Quercetin_3_B_galactoside",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="pp",
            name="Sinapinic_acid",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="pp",
            name="Syringic_acid",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="pp",
            name="Total_polyphenols",
            field=models.FloatField(null=True),
        ),
    ]
