# Generated by Django 4.1.2 on 2022-11-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_fap_cholestrol_fap_docosadienoic_fap_docosahexaenoic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pp",
            name="Quercetin_3_β_galactoside",
        ),
    ]
